name: Deploy Laravel to Staging

on:
  push:
    branches: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Path ke directory aplikasi di server
            APP_DIR=/home/u982131153/domains/artiknesia.com/staging/ARTIKNESIA_v2.0

            # Cek apakah direktori sudah ada, jika belum lakukan clone
            if [ ! -d "$APP_DIR" ]; then
              git clone https://github.com/ahmakbardev/ARTIKNESIA_v2.0.git $APP_DIR
            fi

            cd $APP_DIR

            # Setup environment
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            echo "export PATH=$HOME/bin/node/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile

            # Git operations
            git add .
            git stash
            git pull origin develop

            # Node.js setup
            which node
            node -v
            npm -v
            npm install --legacy-peer-deps
            npm run prod

            # Composer setup
            source ~/.bash_profile
            which composer
            composer --version
            composer install --no-dev --optimize-autoloader
            composer update --no-dev

            # Laravel commands
            php artisan key:generate
            php artisan migrate --force
            php artisan route:clear
            php artisan config:cache
            php artisan optimize

            # Symlink ke public_html jika belum ada
            if [ ! -L "/home/u982131153/domains/artiknesia.com/public_html/staging" ]; then
              ln -s $APP_DIR/public/* /home/u982131153/domains/artiknesia.com/public_html/staging
            fi
