name: Deploy Laravel to Production

on:
  push:
    branches: [main-#1]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ARTIKNESIA_v2.0 to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Path ke direktori project di server
            PROJECT_DIR=/home/u982131153/domains/artiknesia.com/ARTIKNESIA_v2.0

            # Pastikan direktori sudah ada
            if [ ! -d "$PROJECT_DIR" ]; then
              git clone https://github.com/ahmakbardev/ARTIKNESIA_v2.0.git $PROJECT_DIR
            fi

            cd $PROJECT_DIR

            # Setup environment
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            echo "export PATH=$HOME/bin/node/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile

            # Pull kode terbaru dari main
            git reset --hard
            git stash
            git pull origin main

            # Node.js setup
            which node
            node -v
            npm -v
            npm install --legacy-peer-deps
            npm run prod

            # Composer setup
            which composer
            $HOME/bin/composer --version
            $HOME/bin/composer install --no-dev --optimize-autoloader
            $HOME/bin/composer update --no-dev

            # Laravel setup
            php artisan key:generate
            php artisan migrate --force
            php artisan route:clear
            php artisan config:cache
            php artisan storage:link
            php artisan optimize

            # Setup symlink ke public_html jika belum ada
            if [ ! -L "/home/u982131153/domains/artiknesia.com/public_html" ]; then
              ln -s $PROJECT_DIR/public/* /home/u982131153/domains/artiknesia.com/public_html
            fi
